version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: akash
      MONGO_INITDB_ROOT_PASSWORD: gupta

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: akash
      ME_CONFIG_MONGODB_ADMINPASSWORD: gupta
      ME_CONFIG_MONGODB_URL: mongodb://akash:gupta@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  backend:
    image: idudar-backend
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      - mongo
    environment:
      DATABASE: "mongodb://akash:gupta@mongo:27017/"
      RESEND_API: "your_resend_api"
      PENAI_API_KEY: "your_openai_api_key"
      JWT_SECRET: "akashgpt"
      NODE_ENV: "production"
      OPENSSL_CONF: "/dev/null"
      PUBLIC_SERVER_FILE: "http://localhost:8888/"
